### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by mgacy** [lytics/ios-sdk#116]
Issues with the documentation at https://docs.lytics.com/docs/sdk-for-ios

Organized by section

### Overview

- link to Android SDK is broken

### About the Lytics SDK for iOS

- Xcode required version: I'm not aware of any issues with Swift `5.7.0` or `5.7.1` that would require Xcode `14.2`; `14.0+` should be sufficient (though newer is typically preferable) 

#### Before You Begin

- Xcode 14.0 + should be sufficient
- remove `The binary distribution files of the SDK have been built for iOS 8.`; this is distrubuted as a package rather than as a binary

#### Step 2. Configure the SDK

The API token is now passed separately:

```swift
Lytics.shared.start(apiToken: "YOUR-VALID-LYTICS-API-TOKEN")
```

### Configuration

**Remove from Table:**

- `apiKey`: this is now required to be passed to `Lytics.shared.start(apiToken:configure:)` and is no longer part of `LyticsConfiguration`

Additionally, the following are unsupported following the resolution of #56

- `trackScreenViews`
- `trackPushNotifications`
- `trackDeepLinks`

I have a PR -- #119 -- removing them from the code

**Add to Table:**

| Parameter                | Description                                                                         | Type   | Default Value                      |
| ------------------------ | ----------------------------------------------------------------------------------- | ------ | ---------------------------------- |
| `requireConsent`         | A Boolean value indicating whether a user must explicitly opt-in to event tracking. | Bool   | false                              |
| `maxLoadRetryAttempts`   | The maximum number of times to retry failed load requests before throwing an error. | Int    | 1                                  |
| `maxUploadRetryAttempts` | The maximum number of times to try and resend an event on failure.                  | Int    | 3                                  |
| `defaultTable`           | The table used when fetching user profiles.                                         | String | user                               |
| MAYBE (not sure if there's reason to document these for typical usage): ||||
| `collectionEndpoint`     | The data upload endpoint.                                                           | URL    | https://api.lytics.io/collect/json |
| `entityEndpoint`         | The entity (personalization or profile) endpoint.                                   | URL    | https://api.lytics.io/api/entity   |

**Change in Table:**

- `logLevel`: the type is technically `Optional<LogLevel>`, meaning `.none` is also a possible value

**Change example config**:

```swift
Lytics.shared.start(apiToken: "YOUR-VALID-LYTICS-API-TOKEN") { configuration in 
    configuration.logLevel = .debug 
    configuration.defaultStream = "my_custom_ios_stream" 
    configuration.maxQueueSize = 15
}
```

### Tracking Events

- sample code calls the `identify` method rather than `track`

#### Screen Tracking

In addition to OS version and device model name, the SDK also tracks:

- `identifierForVendor`: A UUID that uniquely identifies a device to the app’s vendor. (`UIDevice.current.identifierForVendor`)
- `orientation`: The physical orientation of the device. (`UIDevice.current.orientation`)
- `userInterfaceIdiom`: The style of interface used on the device. (`UIDevice.current.userInterfaceIdiom`)

---

## Other

- I'm not sure if the intent is for the values for the `Type` columns to represent proper Swift types or more general notions of types, but Swift does not have `Timestamp` or `Map` types
    - `Timestamp` is `Int64` (technically it's `Millisecond`, a type alias for `Int64`)
    - `Map` is more complicated, but `Dictionary` would be closer
- a nit, but `Boolean` should probably be capitalized as it refers to George Boole 

## Missing:

The documentation does not cover the following methods:

- `Lytics.getProfile(_:)`
- `Lytics.continueUserActivity(_:stream:)`
- `Lytics.openURL(_:options:stream:)`
- `Lytics.shortcutItem(_:stream:)`

It also does not cover the SwiftUI helper methods provided by the optional `LyticsUI` library:

- `View.trackContinueUserActivity(_:with:stream:perform:)`
- `View.trackOpenURL(with:stream:perform:)`
- `View.trackScreen(with:stream:name:identifiers:properties:)`

**Comment by RaeEversmann** [comment]
See https://docs.lytics.com/suggested-edits/645e91d4be261600116943a2

**Comment by kgruenef** [comment]
@mgacy the updates should all be visible at https://docs.lytics.com/docs/sdk-for-ios now. Anything remaining before we close this issue?

**Comment by mgacy** [comment]
@kgruenef no, it looks good

**Comment by kgruenef** [comment]
Thanks @mgacy going to close this issue now!
