### ISSUE TITLE
Protect system keys

### ISSUE THREAD

**Issue by markhayden** [lytics/ios-sdk#53]
This is going to likely need some more discussion but at the moment there is nothing that stops me as a user from stubbing my toe and setting a custom IDFA, _UID, etc. value. Maybe this is desired but for things like IDFA we may need to consider locking those keys down. 

In general this is something that can be explored and discussed during implementations vs something we proactively invest in. Just making a note here so it doesn't fall off the radar.

**Comment by mgacy** [comment]
#113 prevents the user from setting `IDFA`

**Comment by markhayden** [comment]
@mgacy already added protection for IDFA and we are going to leave _uid open for the time being. Closing.
