### ISSUE TITLE
`dispatch` function does not appear to flush the queue as expected

### ISSUE THREAD

**Issue by markhayden** [lytics/ios-sdk#59]
In testing the `dispatch` function didn't appear to work as expected. What I would expect it to do is flush whatever is in the queue upon firing that request. 

So for instance if I have a queue limit of 10 that gets flushed every minute based on the config. And then I add three `track` events followed by a `dispatch`, I'd expect to see the subsequent API calls fire near immediately. Instead what I observed was the queue would fall back to the predefined limits and either flush at 10 events in queue or after the minute expired.

**Comment by kgruenef** [comment]
@markhayden based on this update https://github.com/lytics/ios-sdk/issues/59#issuecomment-1412351692 can we close this issue or was there something else you want investigated?
